from pathlib import Path

FIXTURES_BASE_PATH = Path(__file__).parent / Path("./fixtures")
FIXTURES_RECORDS_PATH = FIXTURES_BASE_PATH / "records"
FIXTURES_RECORDS_COLLECTION_PATH = FIXTURES_RECORDS_PATH / "collection.json"
FIXTURES_COMPLETED_RECORD_PATH = FIXTURES_RECORDS_PATH / "completed.json"
FIXTURES_INITIALIZED_RECORD_PATH = FIXTURES_RECORDS_PATH / "initialized.json"
FIXTURES_INTERACTED_RECORD_PATH = FIXTURES_RECORDS_PATH / "interacted.json"
FIXTURES_PAUSED_RECORD_PATH = FIXTURES_RECORDS_PATH / "paused.json"
FIXTURES_PLAYED_RECORD_PATH = FIXTURES_RECORDS_PATH / "played.json"
FIXTURES_SEEKED_RECORD_PATH = FIXTURES_RECORDS_PATH / "seeked.json"
FIXTURES_TERMINATED_RECORD_PATH = FIXTURES_RECORDS_PATH / "terminated.json"
